name: Convert Markdown to PDF
on:
  push:
    branches:
      - main
  workflow_dispatch:
     
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Convert Markdown to PDF
      uses: jakejarvis/markdown-to-pdf@1.2.0
      with:
        files: SOFTWARE/bSolid/Compatibilità/Compatibilità.md
